In [ ]:
!pip install soynlp
!pip install utils
!pip install scipy==1.11.1

Collecting soynlp
  Downloading soynlp-0.0.493-py3-none-any.whl (416 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 416.8/416.8 kB 3.1 MB/s eta 0:00:00
Requirement already satisfied: numpy>=1.12.1 in /usr/local/lib/python3.10/dist-packages (from soynlp) (1.25.2)
Requirement already satisfied: psutil>=5.0.1 in /usr/local/lib/python3.10/dist-packages (from soynlp) (5.9.5)
Requirement already satisfied: scipy>=1.1.0 in /usr/local/lib/python3.10/dist-packages (from soynlp) (1.11.4)
Requirement already satisfied: scikit-learn>=0.20.0 in /usr/local/lib/python3.10/dist-packages (from soynlp) (1.2.2)
Requirement already satisfied: joblib>=1.1.1 in /usr/local/lib/python3.10/dist-packages (from scikit-learn>=0.20.0->soynlp) (1.4.2)
Requirement already satisfied: threadpoolctl>=2.0.0 in /usr/local/lib/python3.10/dist-packages (from scikit-learn>=0.20.0->soynlp) (3.5.0)
Installing collected packages: soynlp
Successfully installed soynlp-0.0.493
Collecting utils
  Downloading utils-1.0.2.tar.gz (13 kB)
  Preparing metadata (setup.py) ... done
Building wheels for collected packages: utils
  Building wheel for utils (setup.py) ... done
  Created wheel for utils: filename=utils-1.0.2-py2.py3-none-any.whl size=13906 sha256=fd1b72067749fe17b7c54c132aa4c6c0b6262b632f8596ca9f3daa3ad72ff1c3
  Stored in directory: /root/.cache/pip/wheels/b8/39/f5/9d0ca31dba85773ececf0a7f5469f18810e1c8a8ed9da28ca7
Successfully built utils
Installing collected packages: utils
Successfully installed utils-1.0.2
Collecting scipy==1.11.1
  Downloading scipy-1.11.1-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (36.3 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 36.3/36.3 MB 35.9 MB/s eta 0:00:00
Requirement already satisfied: numpy<1.28.0,>=1.21.6 in /usr/local/lib/python3.10/dist-packages (from scipy==1.11.1) (1.25.2)
Installing collected packages: scipy
  Attempting uninstall: scipy
    Found existing installation: scipy 1.11.4
    Uninstalling scipy-1.11.4:
      Successfully uninstalled scipy-1.11.4
Successfully installed scipy-1.11.1

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
!unzip -qq '/content/drive/MyDrive/csv.zip'

In [ ]:
import pandas as pd
import numpy as np
import os
from numpy import triu
from gensim.models import word2vec

In [ ]:
def load_csvs(path):
    # 디렉터리 경로 설정
    directory_path = path # 예: '/path/to/csv/CLTUR'

    file_list = os.listdir(directory_path)

    # CSV 파일들만 필터링하여 읽기
    csv_files = [file for file in file_list if file.endswith('.csv')]
    dfs = []
    for csv_file in csv_files:
        file_path = os.path.join(directory_path, csv_file)
        df = pd.read_csv(file_path)
        dfs.append(df)
    return dfs

In [ ]:
def preprocess_dup(df):
	df = df.drop_duplicates(subset=['DATA_TITLE_NM'])
	return df.reset_index()

In [ ]:
def select_col(df):
    print(df.columns)
    seleted_df = df[['DATA_TITLE_NM', 'SUMRY_CN','CTPRVN_NM', 'SIGNGU_NM', 'CORE_KWRD_CN']].reset_index().drop(columns=['index'])
    return seleted_df s

## CLTUR

In [ ]:
path = 'csv/CLTUR'
merged_df_CLTUR = select_col(preprocess_dup(pd.concat(load_csvs(path), ignore_index=True)))

Index(['index', 'DATA_MANAGE_NO', 'DATA_TITLE_NM', 'SUMRY_CN', 'SBJT_NM',
       'MAIN_THUMB_URL', 'CNTNTS_URL', 'CTPRVN_NM', 'SIGNGU_NM', 'ADDR',
       'FSTVL_PROGRM_NM', 'FSTVL_PROGRM_DC', 'REGIST_DE', 'CORE_KWRD_CN',
       'SEXDSTN_CD', 'INTRST_REALM_NM', 'PGE_VIEWS_CO', 'VISIT_CO', 'OPN_DE'],
      dtype='object')
                       DATA_TITLE_NM  \
0    황도수확기에 벌이는 농촌체험축제 '햇사레장호원복숭아축제'
1         매년 9월 해녀박물관에서 열리는 '제주해녀축제'
2         포도의 왕, 거봉을 즐기는 ‘입장 거봉포도축제’
3           새우를 맛깔나게 즐기는 ‘홍성남당항대하축제’
4             동양최대 연꽃방죽에서 열리는 무안연꽃축제
..                               ...
162    찻사발 장인들이 함께 하는 축제 '문경전통찻사발축제'
163             부천시민이 만들고 즐기는 복사골예술제
164  4.29 윤봉길 의사 의거일을 기념하는 매헌윤봉길평화축제
165    소수서원과 선비촌에서 개최되는 '영주한국선비문화축제'
166              1990년부터 열린 여주도자기 축제

                                              SUMRY_CN CTPRVN_NM SIGNGU_NM  \
0    경기도 이천시 장호원읍은 쌀과 복숭아 생산에 적합한 토양을 갖추고 있다. 장호원에서...       경기도       이천시
1    제주해녀축제는 제주해녀문화 홍보와 제주해녀들의 위상과 자긍심을 높이기 위해 제정한 ...   제주특별자치도       제주시
2    충청남도 천안시 입장면은 천안시 북부지역에 위치한 구릉 평야지대의 전형적인 농촌으로...      충청남도       천안시
3    충청남도 홍성군 남당항은 천수만의 끝부분에 위치한 청정 어항으로 과거로부터 대하잡이...      충청남도       홍성군
4    무안연꽃축제는 전라남도 무안군 일로읍 백련지 일대에서 열리는 연꽃축제이다. 무안연꽃...      전라남도       무안군
..                                                 ...       ...       ...
162  문경찻사발축제는 경상북도 문경시에서 찻사발을 주제로 하여 매년 4월 개최되는 축제이...      경상북도       문경시
163  경기도 부천시의 예술인 주도로 1985년부터 해마다 복사꽃이 피는 5월에 개최하는 ...       경기도       부천시
164  충청남도 예산군에는 매헌 윤봉길 의사의 생가와 기념관이 있다. 예산에서 윤봉길 의사...      충청남도       예산군
165  영주한국선비문화축제는 선비의 고장 영주에서 개최되는 축제이다. 영주한국선비문화축제는...      경상북도       영주시
166  여주는 고려시대부터 백자 가마터가 있던 곳이다. 양질의 고령토와 가마불을 땔 소나무...       경기도       여주시

                           CORE_KWRD_CN
0                               황도, 햇사레
1    제주, 해녀, 축제, 물질, 숨비소리, 해녀박물관, 해녀의 날
2                                포도, 거봉
3                       새우, 대하, 남당항, 홍성
4                            백련, 연근, 연잎
..                                  ...
162     문경, 찻사발, 축제, 문경새재, 망댕이, 가마, 도자기
163                      복사꽃, 춤, 노래, 공연
164                       매헌, 윤봉길, 대한독립
165           영주, 선비, 축제, 소수서원, 선비촌, 안향
166                  도자기, 여주, 소나무, 고려백자

[167 rows x 5 columns]

# LCFD

In [ ]:
path = 'csv/LCFD'
merged_df_LCFD = select_col(preprocess_dup(pd.concat(load_csvs(path), ignore_index=True)))
merged_df_LCFD

Index(['index', 'DATA_MANAGE_NO', 'DATA_TITLE_NM', 'SUMRY_CN', 'SBJT_NM',
       'MAIN_THUMB_URL', 'CNTNTS_URL', 'ERA_NM', 'CTPRVN_NM', 'SIGNGU_NM',
       'ADDR', 'RELATE_RSTRNT_NM', 'RSTRNT_TEL_NO', 'RSTRNT_ADDR', 'REGIST_DE',
       'CORE_KWRD_CN', 'SEXDSTN_CD', 'INTRST_REALM_NM', 'PGE_VIEWS_CO',
       'VISIT_CO', 'OPN_DE'],
      dtype='object')

,DATA_TITLE_NM,SUMRY_CN,CTPRVN_NM,SIGNGU_NM,CORE_KWRD_CN
0,겨울 남해의 방파제 낚시로 맛보는 호래기(꼴뚜기)회,‘어물전 망신은 꼴뚜기가 시킨다.’ 이 말은 꼴뚜기가 얼마나 볼품없는 생선으로 인식...,경상남도,거제시,"꼴뚜기, 호래기, 방파제 낚시, 바다 낚시"
1,“새우젓은 1년 되어야 살이 부서지고 젓국물이 구수하죠”,"새우젓은 담그는 시기에 따라 이름이 다르다. 음력 3~4월에 담그면 춘젓, 5월에 ...",충청남도,논산시,"향토음식, 강경젓갈, 동젓, 육젓, 춘첫, 순댓국"
2,이름과 달리 궁중에서 먹는 두텁떡,두텁떡은 떡고물이 흩어져 있고 모양이 깔끔하지는 않지만 먹어 본 사람이 아니면 그 ...,서울특별시,종로구,"두텁떡, 봉우리떡, 궁중, 떡"
3,"제주도만의 족발, 아강발을 아시나요?",한국인이 사랑하는 야식 목록에서 빠질 수 없는 것이 족발이다. 쫀득쫀득하면서 기름진...,NaN,NaN,"아강발, 아강발탕, 아강발국, 족발, 미니족발"
4,둥글게 둥글게...도리뱅뱅이,"프라이팬에 빙어나 피라미, 모래무지 등의 작은 민물생선을 빙 돌려 올려놓고 고추장 ...",충청북도,충주시,"향토음식, 피라미, 빙어, 민물고기, 대청호, 금강"
...,...,...,...,...,...
385,강원도 찰옥수수로 만들어야 맛있는 마약옥수수,"‘마약옥수수’라니, 이름부터 범상치 않다. 마약이 불법인 대한민국에서, 음식 앞에 ...",강원특별자치도,NaN,"강원도, 찰옥수수, 마약, 옥수수, 휴게소, 버터"
386,"충절(忠節)의 고장에서 맛보는 충청도식 막국수, 제천 토리면","토리면은 메밀국수를 삶아 그릇에 담고 동치미국물을 부은 다음 도토리묵, 돼지고기 편...",충청북도,제천시,"제천시, 토리면, 토면, 메밀국수, 향토음식"
387,"솔잎향 그윽해 신선들이 탐낸다는 술, 호산춘",경상북도 문경의 장수 황씨 사정공파 종갓집에서는 집안 대대로 내려오는 술이 있다. ...,경상북도,문경시,"호산춘, 토소구, 무형문화재, 전통주, 경상북도, 문경"
388,"바다의 맛과 향을 비벼보자, 거제도 멍게비빔밥","멍게비빔밥은 살짝 얼린 멍게젓갈에 밥과 함께 김 가루, 참기름, 야채 등을 넣어 비...",경상남도,거제시,"멍게비빔밥, 멍게 젓갈, 멍게젓, 우렁쉥이, 멍게, 거제도, 당뇨병 치료"
389,"달콤하고 꼬들꼬들한 맛, 참소라 숙회","단골 횟집이 있다면, 한 두번 즈음 소라 숙회를 ‘서비스’로 맛본 경험이 있을 것이...",충청남도,태안군,"참소라, 뿔소라, 소라, 숙회"

# MRKT

In [ ]:
path = 'csv/MRKT'
merged_df_MRKT = select_col(preprocess_dup(pd.concat(load_csvs(path), ignore_index=True)))
merged_df_MRKT

Index(['index', 'DATA_MANAGE_NO', 'DATA_TITLE_NM', 'SUMRY_CN', 'SBJT_NM',
       'MIDDL_SBJT_NM', 'MAIN_THUMB_URL', 'CNTNTS_URL', 'ERA_NM', 'CTPRVN_NM',
       'SIGNGU_NM', 'ADDR', 'CTLSTT_LA', 'CTLSTT_LO', 'RELATE_PLACE_NM',
       'REGIST_DE', 'CORE_KWRD_CN', 'SEXDSTN_CD', 'INTRST_REALM_NM',
       'PGE_VIEWS_CO', 'VISIT_CO', 'OPN_DE'],
      dtype='object')

,DATA_TITLE_NM,SUMRY_CN,CTPRVN_NM,SIGNGU_NM,CORE_KWRD_CN
0,소고기 느낌을 주는 현풍시장 수구레국밥,쇠가죽에서 벗겨 낸 질긴 고기를 ‘수구레’라고 한다. 대구광역시 달성군에 위치한 ...,대구광역시,달성군,"현풍시장, 수구레국밥, 도깨비, 달성군, 수구레, 대구광역시, 시장음식"
1,관광열차로 유명해진 정선 5일장,2015년 ‘정선아리랑열차’를 운행하면서 유명해진 5일장이 정선5일장이다. 정선5일...,강원특별자치도,정선군,"정선, 5일장, 관광열차, 아리랑열차, 아리랑시장"
2,육쪽마늘로 만든 먹거리가 풍성한 단양 구경시장,단양팔경은 옛날 얘기. 이제는 단양하면 구경이다. 아름다운 경치를 자랑하는 단양팔경...,충청북도,단양군,"단양, 단양팔경, 구경시장, 마늘, 마늘음식, 육쪽마늘, 단양마늘"
3,장터를 누비는 전문 놀이패 남사당패,"남사당패는 전국의 장터를 떠돌아다니며 농악놀이, 접시 돌리기, 재주넘기, 줄타기, ...",경기도,안성시,"오일장, 장터, 남사당패, 안성남사당, 남사당패놀음, 사당패"
4,조선 후기 화폐 사용을 보여주는 박지원의 소설 「허생전」,「허생전」은 조선 시대 후기에 박지원(朴趾源)이 지은 한문 단편소설이다. 「허생전」...,경기도,안성시,"박지원, 허생전, 한문소설, 소설, 화폐경제, 허생, 시장"
...,...,...,...,...,...
163,엿장수들이 엿을 팔면서 부른 「엿파는소리」,오일장과 농촌의 마을을 다니며 전문적으로 엿을 파는 엿장수들은 「엿 파는 소리」에 ...,NaN,NaN,"엿장수, 엿, 엿타령, 민요, 소리, 엿파는소리"
164,조선시대 남부 최대의 상인 병영상인,강진군 병영성을 중심으로 상권이 형성되어 전라도 일대에서 중심적인 상업지역이 되었다...,전라남도,강진군,"병영, 병영성, 병영상인, 강진군, 청자, 병영면"
165,시장을 흥청거리게 하는 장돌뱅이의 장타령,「장타령」은 장타령꾼들이 장터를 흥청거리게 하고 물건을 팔기 위해 부르던 노래였다....,NaN,NaN,"장터, 오일장, 시장, 장돌뱅이, 보부상, 장타령"
166,보부상들의 치열한 삶을 보여주는 소설 「객주」,김주영의 「객주」는 조선 후기 치열하게 살았던 보부상들의 모습을 보여주는 소설이다....,NaN,NaN,"시장, 김주영, 객주, 보부상, 상인, 소설, 장사의 신"
167,조선 건국에 도움을 준 보부상,전국을 떠돌던 보부상이 전국적 조직체계를 만들 수 있었던 것은 이성계와의 인연으로 ...,충청남도,예산군,"백달원, 이성계, 보부상, 행상, 부상청, 안변의 석왕사"

path = 'csv/MRKT'
merged_df_MRKT = preprocess_dup(pd.concat(load_csvs(path), ignore_index=True))
merged_df_MRKT

# OLD_LOAD

In [ ]:
path = 'csv/OLD_LOAD'
merged_df_OLD_LOAD = select_col(preprocess_dup(pd.concat(load_csvs(path), ignore_index=True)))
merged_df_OLD_LOAD

Index(['index', 'DATA_MANAGE_NO', 'DATA_TITLE_NM', 'SUMRY_CN', 'SBJT_NM',
       'MIDDL_SBJT_NM', 'MAIN_THUMB_URL', 'CNTNTS_URL', 'ERA_NM', 'CTPRVN_NM',
       'SIGNGU_NM', 'ADDR', 'CTLSTT_LA', 'CTLSTT_LO', 'RELATE_PLACE_NM',
       'REGIST_DE', 'CORE_KWRD_CN', 'SEXDSTN_CD', 'INTRST_REALM_NM',
       'PGE_VIEWS_CO', 'VISIT_CO', 'OPN_DE'],
      dtype='object')

,DATA_TITLE_NM,SUMRY_CN,CTPRVN_NM,SIGNGU_NM,CORE_KWRD_CN
0,충청도와 경상도를 잇는 문경새재,문경새재는 조선 시대에 영남지방에서 한양으로 오가던 사람들의 주요 통행로였던 영남대...,경상북도,문경시,"영남대로, 초곡천, 문희, 교귀정, 드라마 뿌리깊은 나무"
1,성곽이란 무엇인가,성곽이란 우리말로 ‘잣’ 또는 ‘재’라고 하며 한자 성(城)은 고대에는 성을 흙으로...,NaN,NaN,"성곽, 흙 토(土)’변, 내성, 외성, 도성, 읍성"
2,환관이 덕을 베풀었다는 인덕원으로 향하던 인덕원길,지금의 경기도 안양시에 있는 인덕원은 조선시대에 여행자들에게 숙박을 제공하던 원이 ...,경기도,안양시,"삼남로, 삼남대로, 인덕원, 내시마을, 경기도 삼남길"
3,제주도로 귀양간 김정희의 추사 유배길,조선시대의 학자이자 예술가인 추사 김정희는 윤상도의 상소에 연루되어 사형을 면하는 ...,제주특별자치도,서귀포시,"추사유배길, 김정희, 추사 적거지, 삼남대로, 관두포, 화북포구, 대정읍, 제주도"
4,하천을 건너기 위해 배를 연결해 만들었던 배다리,조선시대에는 큰 하천을 건너는 다리가 거의 없었다. 한강과 같은 큰 하천을 건너는 ...,서울특별시,용산구,"배다리, 뜬다리, 용산나루, 노량나루, 광나루, 주교, 선교, 선교장, 정약용"
...,...,...,...,...,...
80,장군들이 인정한 무주 적상산성,"절벽으로 이루어진 산 위의 분지를 에워싼 대표적인 방어산성이다. 전체 길이 8,13...",전라북도,무주군,"방어산성, 포곡식, 적상산, 향로봉, 기봉, 적상산 사고, 호국사"
81,"강원도, 충청도, 경상도가 만나는 베틀재길",베틀재는 충청북도 단양군 영춘면 동대리에 있는 해발 651m의 고개이다. 백두대간에...,충청북도,단양군,"남한강, 백두대간, 단양군, 영월군, 영주시, 배틀마을, 소금, 용진나루"
82,"호남의 중심지, 나주읍성","나주읍 중심부에 돌을 쌓아 만든 평지성으로 둘레는 3,530m에 달하며 남북장축의 ...",전라남도,나주시,"평지성, 읍성, 옹성, 고려, 나주목읍성, 남고문, 동점문, 서성문"
83,시대마다 유행타는 남한산성 축성 기술,신라시대에 주장성(晝長城)으로 불린 남한산성은 672년(문무왕 12)에 쌓았으며 주...,경기도,광주시,"주장성, 남한산성, 통일신라 건물지, 수어사 이서, 병자호란"
84,"왕들의 유배지, 거제 둔덕기성",둔덕면과 사등면의 경계지역에 위치한 우봉산 줄기 야산 해발 326m에 위치한 둔덕기...,경상남도,거제시,"폐왕성, 거제 둔덕기성, 정중부의 난, 신라 치소성"

In [ ]:
import re

def preprocessing(text):
    # 개행문자 제거
    text = re.sub('\\\\n', ' ', text)
    # # 한글, 영문만 남기고 모두 제거
    text = re.sub('[^가-힣ㄱ-ㅎㅏ-ㅣa-zA-Z]', ' ', text)
    return text

In [ ]:

final_df = pd.concat([merged_df_CLTUR, merged_df_LCFD, merged_df_OLD_LOAD, merged_df_MRKT])
final_df['sentence']=final_df.apply(lambda row: ' '.join(row.values.astype(str)), axis=1)

sentences=final_df['sentence'].apply(preprocessing)
sentences

0      황도수확기에 벌이는 농촌체험축제  햇사레장호원복숭아축제  경기도 이천시 장호원읍은 ...
1      매년  월 해녀박물관에서 열리는  제주해녀축제  제주해녀축제는 제주해녀문화 홍보와 ...
2      포도의 왕  거봉을 즐기는  입장 거봉포도축제  충청남도 천안시 입장면은 천안시 북...
3      새우를 맛깔나게 즐기는  홍성남당항대하축제  충청남도 홍성군 남당항은 천수만의 끝부...
4      동양최대 연꽃방죽에서 열리는 무안연꽃축제 무안연꽃축제는 전라남도 무안군 일로읍 백련...
                             ...
163    엿장수들이 엿을 팔면서 부른  엿파는소리  오일장과 농촌의 마을을 다니며 전문적으로...
164    조선시대 남부 최대의 상인 병영상인 강진군 병영성을 중심으로 상권이 형성되어 전라도...
165    시장을 흥청거리게 하는 장돌뱅이의 장타령  장타령 은 장타령꾼들이 장터를 흥청거리게...
166    보부상들의 치열한 삶을 보여주는 소설  객주  김주영의  객주 는 조선 후기 치열하...
167    조선 건국에 도움을 준 보부상 전국을 떠돌던 보부상이 전국적 조직체계를 만들 수 있...
Name: sentence, Length: 810, dtype: object

In [ ]:
from soynlp.tokenizer import RegexTokenizer

tokenizer = RegexTokenizer()
tokens = sentences.apply(tokenizer.tokenize)
tokens[:]

/usr/local/lib/python3.10/dist-packages/soynlp/tokenizer/_tokenizer.py:19: FutureWarning: Possible nested set at position 13
  ('english & latin', re.compile(u"[a-zA-ZÀ-ÿ]+[[`']?s]*|[a-zA-ZÀ-ÿ]+", re.UNICODE))

0      [황도수확기에, 벌이는, 농촌체험축제, 햇사레장호원복숭아축제, 경기도, 이천시, 장...
1      [매년, 월, 해녀박물관에서, 열리는, 제주해녀축제, 제주해녀축제는, 제주해녀문화,...
2      [포도의, 왕, 거봉을, 즐기는, 입장, 거봉포도축제, 충청남도, 천안시, 입장면은...
3      [새우를, 맛깔나게, 즐기는, 홍성남당항대하축제, 충청남도, 홍성군, 남당항은, 천...
4      [동양최대, 연꽃방죽에서, 열리는, 무안연꽃축제, 무안연꽃축제는, 전라남도, 무안군...
                             ...
163    [엿장수들이, 엿을, 팔면서, 부른, 엿파는소리, 오일장과, 농촌의, 마을을, 다니...
164    [조선시대, 남부, 최대의, 상인, 병영상인, 강진군, 병영성을, 중심으로, 상권이...
165    [시장을, 흥청거리게, 하는, 장돌뱅이의, 장타령, 장타령, 은, 장타령꾼들이, 장...
166    [보부상들의, 치열한, 삶을, 보여주는, 소설, 객주, 김주영의, 객주, 는, 조선...
167    [조선, 건국에, 도움을, 준, 보부상, 전국을, 떠돌던, 보부상이, 전국적, 조직...
Name: sentence, Length: 810, dtype: object

In [ ]:
model = word2vec.Word2Vec(tokens, min_count=1)

In [ ]:

# 인덱스와 키 매핑 리스트
words = model.wv.index_to_key
print(len(words))
# 예제: 특정 단어의 벡터 가져오기
model.wv.most_similar('옷감')  # 특정 단어의 벡터를 가져옵니다.

21704

[('넣는다고', 0.37760889530181885),
 ('대하', 0.36198097467422485),
 ('독도새우가', 0.34275075793266296),
 ('막걸리로', 0.3425430953502655),
 ('출토되었다', 0.33919548988342285),
 ('차이점이다', 0.33715781569480896),
 ('쑥죽', 0.3366265892982483),
 ('유전병', 0.3331007659435272),
 ('급수의', 0.3314002752304077),
 ('끝나고', 0.3257290720939636)]

In [ ]:
# 지역 이름과 키워드 열만 유지
final_df = final_df[['SIGNGU_NM', 'CORE_KWRD_CN']].reset_index().drop(columns=['index'])
final_df['CORE_KWRD_CN'] = final_df['CORE_KWRD_CN'].astype(str)
# 시군구 이름으로 키워드 행 묶기
final_df = final_df.groupby('SIGNGU_NM')['CORE_KWRD_CN'].apply(lambda x: ', '.join(x)).reset_index()
final_df
# print(final_df[final_df['SIGNGU_NM'] == '가평군']['CORE_KWRD_CN'])

    SIGNGU_NM                                       CORE_KWRD_CN
0         가평군            가평, 자라섬, 재즈, 페스티벌, 청평댐, 땅콩섬, 중국섬, 재즈막걸리
1         강남구                                 패션쇼, 디자인, 청담동, 압구정
2         강동구                                      신석기, 선사시대, 시간
3         강릉시  향토음식, 모두부, 비지, 강릉, 초당두부, 초당, 감자, 송편, 향토음식, 강원도...
4         강서구               허준, 동의보감, 의성, 부산, 가덕도, 대구탕, 대구, 향토음식
..        ...                                                ...
165       홍천군                   강원도, 홍천군, 홍천시장, 홍천중앙시장, 홍천장, 오일장
166       화성시  정조, 과천길, 시흥길, 만안교, 대황교, 시흥행궁, 수원화성, 현륭원, 만세운동,...
167       화순군                        운주사, 불교축제, 민간, 동지팥죽, 새알, 팥죽
168       화천군  얼음, 화천, 산천어, 축제, 화천천, 강원도, 화천군, 시장, 화천장, 화천시장,...
169       횡성군  한우, 축제, 섬강, 한우리, 안흥, 찐빵, 고속도로, 휴게소, 팥, 앙금, 강원도...

[170 rows x 2 columns]

In [ ]:
def preprocess_text(text):
    if isinstance(text, str):
        return re.sub(r'[^\w\s]', '', text)
    else:
        return ''

In [ ]:
def find_similar_region(input_region):
    input_keywords = preprocess_text(final_df[final_df['SIGNGU_NM'] == input_region]['CORE_KWRD_CN'].values[0])
    similar_regions = []
    for index, row in final_df.iterrows():
        region = row['SIGNGU_NM']
        if region != input_region:
            region_keywords = preprocess_text(row['CORE_KWRD_CN'])
            if (region_keywords):
              # print(input_keywords, region_keywords)
              similarity = model.wv.n_similarity(input_keywords, region_keywords)
              similar_regions.append((region, similarity))

    similar_regions.sort(key=lambda x: x[1], reverse=True)
    top_similar_regions = [region for region, _ in similar_regions[:5]]
    # 가장 낮은 평균 유사도 초기화
    lowest_avg_similarity = float('inf')
    lowest_avg_similarity_region = None

    # 각 상위 5개 지역에 대해 나머지 지역들과의 평균 유사도 계산
    for top_region in top_similar_regions:
        similarities = []
        for index, row in final_df.iterrows():
            region = row['SIGNGU_NM']
            if region not in top_similar_regions:
                region_keywords = preprocess_text(row['CORE_KWRD_CN'])
                similarity = model.wv.n_similarity(input_keywords, region_keywords)
                similarities.append(similarity)

        # 평균 유사도 계산
        avg_similarity = sum(similarities) / len(similarities)

        # 가장 낮은 평균 유사도와 그 지역 저장
        if avg_similarity < lowest_avg_similarity:
            lowest_avg_similarity = avg_similarity
            lowest_avg_similarity_region = top_region

    return similar_regions, lowest_avg_similarity_region, lowest_avg_similarity

# 테스트
input_region = '화성시'
similar_regions, lowest_region, lowest_similarity = find_similar_region(input_region)
print("입력된 지역의 키워드: " + final_df[final_df['SIGNGU_NM'] == '고창군']['CORE_KWRD_CN'])

# 출력 형식 설정
print("유사도 Top 5 지역:")
for region, similarity in similar_regions[:5]:
    print(f"{region}: {similarity}")

print()
print(f"입력된 지역 '{input_region}'과(와) 유사도 Top 5 지역 중 가장 낮은 평균 유사도를 가진 지역은 '{lowest_region}', 다른 지역과의 평균 유사도: {lowest_similarity}")

13    입력된 지역의 키워드: 고창, 읍성, 모양성, 축제, 답성놀이, 모양성제, 전라북도...
Name: CORE_KWRD_CN, dtype: object
유사도 Top 5 지역:
안양시: 0.6896129846572876
동대문구: 0.6660357713699341
중구: 0.6359043121337891
수원시: 0.6332691311836243
달성군: 0.631657063961029

입력된 지역 '화성시'과(와) 유사도 Top 5 지역 중 가장 낮은 평균 유사도를 가진 지역은 '안양시', 다른 지역과의 평균 유사도: 0.34327417160525464